format = """$directory$git_branch$git_status$character """
add_newline = false

[character]
success_symbol = """[>](bold green)"""
error_symbol = """[>](bold red)"""

[git_branch]
format = """[$symbol $branch(:$remote_branch)]($style)"""
symbol = ""
style = "bold purple"

[git_status]
format = """[$all_status$ahead_behind$ahead_count$behind_count]($style)"""
